import type { GestureBinding } from '@/types/gesture';
import {
  CUTOFF_MAX_HZ, CUTOFF_MIN_HZ, PITCH_MAX_MIDI, PITCH_MIN_MIDI,
  RESONANCE_MAX, RESONANCE_MIN, DEFAULT_SMOOTHING_MS,
  AMPLITUDE_MAX, AMPLITUDE_MIN,
  DRIVE_MIN, DRIVE_MAX,
  FX_MIX_MIN, FX_MIX_MAX,
  REVERB_MIX_MAX,
  LFO_DEPTH_MIN, LFO_DEPTH_MAX,
  LFO_RATE_MIN_HZ, LFO_RATE_MAX_HZ,
  MODULATION_INDEX_MIN, MODULATION_INDEX_MAX,
  SUSTAIN_MIN, SUSTAIN_MAX,
} from './audio';

export const DEFAULT_GESTURE_BINDINGS: readonly GestureBinding[] = [
  {
    id: 'rh-y-pitch',
    hand: 'Right',
    feature: 'positionY',
    target: 'pitch',
    curve: 'quantizedScale',
    inputMin: 0, inputMax: 1,
    outputMin: PITCH_MIN_MIDI, outputMax: PITCH_MAX_MIDI,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'rh-pinch-amp',
    hand: 'Right',
    feature: 'pinchDistance',
    target: 'amplitude',
    curve: 'linear',
    inputMin: 0.02, inputMax: 0.25,
    outputMin: AMPLITUDE_MIN, outputMax: AMPLITUDE_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'lh-x-cutoff',
    hand: 'Left',
    feature: 'positionX',
    target: 'cutoff',
    curve: 'exponential',
    inputMin: 0, inputMax: 1,
    outputMin: CUTOFF_MIN_HZ, outputMax: CUTOFF_MAX_HZ,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'lh-pinch-res',
    hand: 'Left',
    feature: 'pinchDistance',
    target: 'resonance',
    curve: 'linear',
    inputMin: 0.02, inputMax: 0.25,
    outputMin: RESONANCE_MIN, outputMax: RESONANCE_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'lh-palm-drive',
    hand: 'Left',
    feature: 'palmOpenness',
    target: 'drive',
    curve: 'linear',
    inputMin: 0, inputMax: 1,
    outputMin: DRIVE_MIN, outputMax: DRIVE_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'rh-palm-lfodepth',
    hand: 'Right',
    feature: 'palmOpenness',
    target: 'lfoDepth',
    curve: 'linear',
    inputMin: 0, inputMax: 1,
    outputMin: LFO_DEPTH_MIN, outputMax: LFO_DEPTH_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'both-handsdist-reverb',
    hand: 'both',
    feature: 'handsDistance',
    target: 'reverbMix',
    curve: 'linear',
    inputMin: 0.1, inputMax: 0.8,
    outputMin: FX_MIX_MIN, outputMax: REVERB_MIX_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'rh-tilt-lforate',
    hand: 'Right',
    feature: 'handTilt',
    target: 'lfoRate',
    curve: 'linear',
    inputMin: -1, inputMax: 1,
    outputMin: LFO_RATE_MIN_HZ, outputMax: LFO_RATE_MAX_HZ,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'lh-velocity-delaymix',
    hand: 'Left',
    feature: 'handVelocity',
    target: 'delayMix',
    curve: 'linear',
    inputMin: 0, inputMax: 1,
    outputMin: FX_MIX_MIN, outputMax: FX_MIX_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'rh-depth-chorusmix',
    hand: 'Right',
    feature: 'handDepth',
    target: 'chorusMix',
    curve: 'linear',
    inputMin: 0, inputMax: 1,
    outputMin: FX_MIX_MIN, outputMax: FX_MIX_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'lh-middlepinch-modindex',
    hand: 'Left',
    feature: 'middlePinch',
    target: 'modulationIndex',
    curve: 'linear',
    inputMin: 0.02, inputMax: 0.25,
    outputMin: MODULATION_INDEX_MIN, outputMax: MODULATION_INDEX_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
  {
    id: 'rh-spread-sustain',
    hand: 'Right',
    feature: 'fingerSpread',
    target: 'sustain',
    curve: 'linear',
    inputMin: 0, inputMax: 1,
    outputMin: SUSTAIN_MIN, outputMax: SUSTAIN_MAX,
    smoothingMs: DEFAULT_SMOOTHING_MS,
  },
];
